### ISSUE TITLE
Authentication bypass

### ISSUE THREAD

**Issue by aldaor** [berkus/usercake#1]
Please note that the authentication can be bypassed by submitting "/" before and after Url Path, e.g. http://www.target.com//admin_users.php/ or http://www.target.com//admin_pages.php/ etc. If some pages redirects to `login.php` just create an account via `register.php` URL. 
Inside there are some RXSS and SXSS vulnerabilities as well as Improper Access Contol at `/admin_pages.php/` where unauthenticated attacker can delete any user.

**Comment by berkus** [comment]
👍🏼
